---
title: Lifestone Church
timezone: UTC
collections:
  pages:
    title: Pages
    output: true
    permalink: "/:path/"
  devotionals:
    title: Devotionals
    output: true
    permalink: "/resources/devotionals/:title/"
  events:
    output: true
    permalink: /events/:path/
  sermons:
    title: Sermons
    output: true
    permalink: "/resources/sermons/:title/"
defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: page
  -
    scope:
      type: events
    values:
      layout: fullPage
  - scope:
      path: ''
      type: devotionals
    values:
      layout: devotional
  - scope:
      path: ''
      type: sermons
    values:
      layout: sermon
baseurl: 
url: http://www.lifestonechurch.herokuapp.com
description: A Bible-based church in Herriman, Utah.
markdown: kramdown
kramdown:
  auto_ids: true
managerName: Adam Harris
managerEmail: adam@mountainview-webdesign.com
organizationName: Lifestone Church
squareLogo: assets/images/logo2.jpg
podcastSubtitle: Messages from Sunday morning worship at Lifestone Church
permalink: "/:categories/:title/"
google_analytics_code: UA--1
gems:
  - jekyll-redirect-from
